### ISSUE TITLE
Can't access devices

### ISSUE THREAD

**Issue by matthias-scholze** [HendrikRoth/node-red-contrib-arlo#3]
Hello,

thanks for this addon. 

At the moment I can't use it beacause I can't determine the arlo devices. I get the following errror message:

[0.19.4] Node-RED

    Deploy

node properties
Service
Name
Basestation
node settings

TypeError: Cannot read property 'arlo' of undefined
    at /data/node_modules/node-red-contrib-arlo/arlo.js:10:9
    at Layer.handle [as handle_request] (/usr/src/node-red/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/node-red/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/src/node-red/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/src/node-red/node_modules/express/lib/router/layer.js:95:5)
    at /usr/src/node-red/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/usr/src/node-red/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/src/node-red/node_modules/express/lib/router/index.js:275:10)
    at /usr/src/node-red/node_modules/express/lib/application.js:233:9
    at /usr/src/node-red/node_modules/express/lib/router/index.js:635:15
    at next (/usr/src/node-red/node_modules/express/lib/router/index.js:260:14)
    at expressInit (/usr/src/node-red/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/usr/src/node-red/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/node-red/node_modules/express/lib/router/index.js:317:13)
    at /usr/src/node-red/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/src/node-red/node_modules/express/lib/router/index.js:335:12)

Regards
Matthias

**Comment by macinspak** [comment]
You need to deploy the flow first, then use the search button
