### ISSUE TITLE
Error on getting devices

### ISSUE THREAD

**Issue by MatGriffin** [HendrikRoth/node-red-contrib-arlo#4]
`
TypeError: Cannot read property 'arlo' of undefined
    at /opt/node_modules/node-red-contrib-arlo/arlo.js:10:10
    at Layer.handle [as handle_request] (/opt/node_modules/express/lib/router/layer.js:95:5)
    at next (/opt/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/opt/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/opt/node_modules/express/lib/router/layer.js:95:5)
    at /opt/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/opt/node_modules/express/lib/router/index.js:335:12)
    at next (/opt/node_modules/express/lib/router/index.js:275:10)
    at /opt/node_modules/express/lib/application.js:233:9
    at /opt/node_modules/express/lib/router/index.js:635:15
    at next (/opt/node_modules/express/lib/router/index.js:260:14)
    at expressInit (/opt/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/opt/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/opt/node_modules/express/lib/router/index.js:317:13)
    at /opt/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/opt/node_modules/express/lib/router/index.js:335:12)

70%`

**Comment by seanpwelch90** [comment]
Not sure if you were ever able to solve this, but I was having a similar issue searching for devices and getting an error. If you **deploy** the node first, then attempt to get devices, the search returns the proper results. Hope that helps.

**Comment by macinspak** [comment]
Did that, but the dropdown doesn't show any devices

**Comment by Cjkeenan** [comment]
I am having this issue as well. It originally worked and then suddenly did not, and I am not sure what changed. Below is my error log. I believe the issue is associated with 2FA, are there any plans to support this given Netgear is forcing this coming soon?
```
TypeError: Cannot read property 'arlo' of undefined
    at /mnt/dietpi_userdata/node-red/node_modules/node-red-contrib-arlo/arlo.js:10:10
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/node-red/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/local/lib/node_modules/node-red/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
    at /usr/local/lib/node_modules/node-red/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/usr/local/lib/node_modules/node-red/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/local/lib/node_modules/node-red/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/usr/local/lib/node_modules/node-red/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
```
